### PR TITLE
[WIP] Working docker file. 

### PR DESCRIPTION
**Pull request by hrishikeshvganu**
**Submitting PR as per mail below**
---------- Forwarded message ----------
From: srush <noreply@forum.opennmt.net>
Date: Tue, Jan 17, 2017 at 9:41 PM
Subject: [OpenNMT Forum] [Support] Docker image broken?
To: <>

srush	srush 
January 17             
Hi @wabbit, can you send the errors?

Do you have a docker file for your install? We can make that the official one if you got it working cleanly.

Visit Topic to respond.

In Reply To

jean.senellart	jean.senellart 
January 16
Hi @Wabbit - @srush is maintaining the docker, he is off till wednesday and will come back to you just after.
Visit Topic to respond.

To unsubscribe from these emails, click here.

### CODE REVIEW

**Comment by guillaumekln** [comment]
There is a [dedicated repository](https://github.com/OpenNMT/Docker) for the Dockerfile. I believe you should submit your changes there.

cc @srush

**Comment by srush** [comment]
Thanks @hrishikeshvganu . Do you know if we can have the Dockerfile automatically `git pull` and install the latest version of the repo when run? 

Maybe we can put it in `tools/Dockerfile`? Seems like overkill to have a separate repo for one file, and similarly to .travis.yml and rockspec. it needs to change if something is added. 

Also lets add all the optional deps too, i.e.  

sudo apt-get install libzmq-dev

luarocks install json

luarocks install lua-zmq ZEROMQ_LIBDIR=/usr/lib/x86_64-linux-gnu/ ZEROMQ_INCDIR=/usr/include

**Comment by srush** [comment]
(discussing in https://gitter.im/OpenNMT/openmt if you are interested.)

**Comment by srush** [comment]
We decided on using `.Dockerfile` in the root directory. I set up https://hub.docker.com/r/opennmt/opennmt/ to automatically build `opennmt/opennmt:latest` from that file. Let me know when that is ready and I will set up the docs.

**Pull request merged**
