### PR TITLE
CrayonLogger: OpenNMT metrics visualization with TensorBoard

### PR DESCRIPTION
**Pull request by pltrdy**
As discussed here: http://forum.opennmt.net/t/support-crayon-logging/237

### CODE REVIEW

**Comment by srush** [comment]
Looks great. Can you fix the failing checks first though. Be sure to run luacheck on all your files:

Checking onmt/utils/CrayonLogger.lua              2 warnings
    onmt/utils/CrayonLogger.lua:18:1: line contains only whitespace
    onmt/utils/CrayonLogger.lua:24:1: line contains only whitespace

**Comment by pltrdy** [comment]
Fixed.

**Comment by srush** [comment]
Oh one other thing. Since this is a new file, you need to add it to https://github.com/OpenNMT/OpenNMT/blob/master/rocks/opennmt-scm-1.rockspec

**Comment by pltrdy** [comment]
Good to know. 
Updated.

**Pull request merged**
