### PR TITLE
Save and Restore RNG States

### PR DESCRIPTION
**Pull request by jsenellart-systran**
when saving checkpoint - save also RNG States so that `train_from` starts from exactly the same state

### CODE REVIEW

**Comment by vince62s** [comment]
@guillaumekln @jsenellart-systran ,
For my need ( I use the train_from without the -continue option) I removed the 2 lines here:
https://github.com/jsenellart-systran/OpenNMT/blob/70b7749952c06cfb09c48c5791d340a422484d54/onmt/train/Checkpoint.lua#L136-L137
I think they are not mandatory. Can yo please confirm ?

Otherwise, we can just retrieve the RG states info just before setting to NIL and restate it.

Also, I really think that this "-continue" option is a little confusing.
What about:
if we train_from then behavior is the same as -continue EXCEPT for all options that are passed through command line ?
To me it would be clearer.

**Comment by guillaumekln** [comment]
If `checkpoint.info` is not `nil` the training will just reuse the batch order (for intermediate models) and optimization states (for non SGD methods) of the previous model.

---

For the `-continue` behavior, maybe it is worth opening a thread on the forum to discuss about it. With @jsenellart-systran recent changes we are now able to know whether an option was set or not (it was not the case before) so this new approach can be considered.

**Comment by vince62s** [comment]
But this is the same behavior as with -continue, no ?

**Comment by guillaumekln** [comment]
Yes, that is why previous training information are cleared when not using `-continue`.

**Pull request merged**
