### PR TITLE
Travis docker build

### PR DESCRIPTION
**Pull request by aurelien-coquard**
The aim of this PR is to use the Dockerfile included in the repository to setup the test environment for travis-ci.
I can see the following advantages to do so:
- Speed up travis-ci jobs (I observed that the travis-ci job takes only ten minutes now, to be compared with the twenty minutes before: [build #9](https://travis-ci.org/aurelien-coquard/OpenNMT/builds/275604717))
- Validate that the Dockerfile is still compatible with current code (detect if Dockerfile needs an update)
- Avoid code duplication (similar code in `Dockerfile` and in `.travis.yml`)

In order not to rebuild the whole Docker image each time, the travis-ci script pull and push images from a Docker repository. I temporally used my repository on [Docker Hub](https://hub.docker.com/u/aureliencoquard/) as I currently don't have access to [OpenNMT repository](https://hub.docker.com/u/opennmt/), but this is the one that should be used on the official github repository.

So, if this PR is accepted, before merging it, all references to my Docker repository should be replaced by references to OpenNMT official repository. Also, credentials to connect this Docker repository should be added to travis OpenNMT account settings (see [Travis Documentation](https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry)). Indeed, the new travis-ci job, appart from executing the tests, is also responsible for updating Docker images when Dockerfile changes and needs credentials to push to Docker repository.

For reference, here is the TODO list before merging:
- [x] tag and push the first image to [opennmt/opennmt repo](https://hub.docker.com/r/opennmt/opennmt/):
```
$ docker pull aureliencoquard/opennmt:latest
$ docker tag aureliencoquard/opennmt:latest opennmt/opennmt:8.0
$ docker tag aureliencoquard/opennmt:latest opennmt/opennmt:latest
$ docker push opennmt/opennmt
```
- [ ] Add Docker credentials for opennmt to [travis-ci setting](https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry)
- [x] Modify `.travis.yml`: replace all references to 'aureliencoquard' with 'opennmt'
- [x] Commit and push

### CODE REVIEW

**Comment by aurelien-coquard** [comment]
Please note also that as the travis-ci job will now update docker images on docker repository, automatic builds on Docker Hub should be disabled for this project.

**Comment by aurelien-coquard** [comment]
I've pushed a new image to opennmt/opennmt docker repo, and modified `.travis.yml` to use this repo. So, only remains to add docker hub credentials to [travis-ci setting](https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry)

**Comment by jsenellart** [comment]
@aurelien-coquard - please send me the credentials by email, and I will be adding them. (or what do I need to do to give you access on travis admin?)

**Comment by guillaumekln** [comment]
Credentials in travis-ci were updated. Merging...

**Pull request merged**
