### PR TITLE
Update Log.lua

### PR DESCRIPTION
**Pull request by da03**
add onmt.logging for maintaining logs at different levels in a log file.

### CODE REVIEW

**Comment by guillaumekln** [comment]
Can this be somehow used to log on the standard output as well? It would be nice to have common way to log messages in the shell or in a file.

Additionally this should typically have its own file, maybe called `Logger`.

**Comment by da03** [comment]
Sure I'll update it.

**Comment by da03** [comment]
Updated. Example usage:

1. Only output to stdout:

```
logging = onmt.Logger()
logging:info('%s is an extension of OpenNMT.', 'Im2Text')
```

2. Output to stdout and a file simultaneously:

```
logging = onmt.Logger('log.txt')
logging:warning('%s is an extension of OpenNMT.', 'Im2Text')
logging:shutDown()
```

3. Output to a file:

```
logging = onmt.Logger('log.txt', true)
logging:warning('%s is an extension of OpenNMT.', 'Im2Text')
logging:shutDown()
```

**Comment by da03** [comment]
Updated. Example usage:

1. Only output to stdout:

```
logging = onmt.utils.Logger.new()
logging:info('%s is an extension of OpenNMT.', 'Im2Text')
```

2. Output to stdout and a file simultaneously:

```
logging = onmt.utils.Logger.new('log.txt')
logging:warning('%s is an extension of OpenNMT.', 'Im2Text')
logging:shutDown()
```

3. Output to a file:

```
logging = onmt.utils.Logger.new('log.txt', true)
logging:error('%s is an extension of OpenNMT.', 'Im2Text')
logging:shutDown()
```

**Pull request merged**
